# Generated by Django 5.1.4 on 2024-12-07 17:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_yummy_likes_recipelikes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipelikes',
            unique_together={('user', 'recipe')},
        ),
    ]
