# Generated by Django 5.1.4 on 2024-12-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_recipelikes_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipelikes',
            name='isLiked',
            field=models.BooleanField(default=True),
        ),
    ]
