# Generated by Django 5.1.4 on 2024-12-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_recipelikes_isliked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipelikes',
            old_name='isLiked',
            new_name='isLikedPost',
        ),
    ]
