# Generated by Django 5.1.4 on 2024-12-10 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_isliked_recipelikes_islikedpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipelikes',
            name='created',
        ),
    ]
