# Generated by Django 5.1.3 on 2024-11-30 18:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chai_Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('imange', models.ImageField(upload_to='chai_Images/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ML', 'MASALA'), ('EC', 'ELAICHI'), ('GR', 'GINGER'), ('PL', 'PLAIN'), ('VL', 'VANILA'), ('TL', 'TULSI')], default='ML', max_length=5)),
            ],
        ),
    ]
