# Generated by Django 5.1.4 on 2024-12-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yummy',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='yummy_images/'),
        ),
    ]
