# Generated by Django 5.1.3 on 2024-11-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chai_variety',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
