# Generated by Django 5.1.3 on 2024-11-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai_app', '0002_chai_variety_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chai_variety',
            name='description',
            field=models.TextField(default='Great Tea'),
        ),
        migrations.AlterField(
            model_name='chai_variety',
            name='imange',
            field=models.ImageField(upload_to='chai_images/'),
        ),
    ]
