# Generated by Django 5.1.4 on 2024-12-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_yummy_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='yummy',
            name='recipe_name',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='yummy',
            name='images',
            field=models.ImageField(upload_to='yummy_images/'),
        ),
    ]
