# Generated by Django 5.1.3 on 2024-11-30 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai_app', '0003_alter_chai_variety_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chai_variety',
            old_name='imange',
            new_name='image',
        ),
    ]
