# Generated by Django 5.1.3 on 2024-12-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai_app', '0005_certificates_chai_reviews_stores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stores',
            old_name='avail_varieties',
            new_name='avail',
        ),
        migrations.AlterField(
            model_name='chai_variety',
            name='type',
            field=models.CharField(choices=[('ML', 'MASALA'), ('EC', 'ELAICHI'), ('GR', 'GINGER'), ('PL', 'PLAIN'), ('VL', 'VANILA'), ('TL', 'TULSI')], default='ML', max_length=3),
        ),
    ]
